server:
  port: 8070
spring:
  application:
    name: player-service
  sleuth:
    sampler:
      probability: 100
  zipkin:
    base-url: http://localhost:9411/
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: codenameduet-playerservice
#    password: codenameduet-playerservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




