custom:
  db:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: codenameduet-playerservice
    password: codenameduet-playerservice

h2:
  console:
    enabled: true
    path: /console
